# Generated by Django 6.0.2 on 2026-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
