# Generated by Django 6.0.2 on 2026-03-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_encryption_key_lesson_hls_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_includes',
            field=models.TextField(blank=True, help_text='Newline-separated list of items included in the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Newline-separated list of what students will learn'),
        ),
    ]
