# Generated by Django 6.0.2 on 2026-03-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_includes_course_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/'),
        ),
    ]
